# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b4e08f444bcb1582570b034b39f2e9c7fd0e193625c68b32960ad80a3d24ed36754faa4bfd963fd3bc0cd5c6122f5cfa01f73237a3da3c935e027d3ad21f1d3b

test:
  secret_key_base: 43a0f3d778475230b8ad2cae22de1963ae692689f1b7fb623b587979d73394d55b151276c3afbd766245a341c04e7bd9b724c737b6d4462c5b0fd294a3c52ccf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
